-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.comentario
(
    id_comentario bigint NOT NULL DEFAULT nextval('comentario_id_comentario_seq'::regclass),
    contenido text COLLATE pg_catalog."default" NOT NULL,
    id_usuario integer NOT NULL DEFAULT 1,
    id_post integer NOT NULL DEFAULT 1,
    CONSTRAINT comentario_pkey PRIMARY KEY (id_comentario)
);

CREATE TABLE IF NOT EXISTS public.post
(
    id_post bigint NOT NULL DEFAULT nextval('post_id_post_seq'::regclass),
    descripcion character varying(100) COLLATE pg_catalog."default",
    url_imagen text COLLATE pg_catalog."default" NOT NULL,
    id_usuario bigint NOT NULL DEFAULT 1,
    CONSTRAINT post_pkey PRIMARY KEY (id_post)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario bigint NOT NULL DEFAULT nextval('usuario_id_seq'::regclass),
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    dia_ingreso date,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario)
);

ALTER TABLE IF EXISTS public.comentario
    ADD CONSTRAINT fk_id_port FOREIGN KEY (id_usuario)
    REFERENCES public.post (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comentario
    ADD CONSTRAINT fk_id_usuario FOREIGN KEY (id_usuario)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.post
    ADD CONSTRAINT fk_id_usurio FOREIGN KEY (id_usuario)
    REFERENCES public.usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;